package service.http;

public enum Endpoint {
    GET_EPIC, GET_EPICS,
    GET_EPIC_SUBTASKS, GET_HISTORY,
    GET_PRIORITIZED_TASKS, GET_SUBTASK, GET_SUBTASKS,
    GET_TASK, GET_TASKS,
    POST_CREATE_TASK, POST_UPDATE_TASK,
    POST_CREATE_SUBTASK, POST_UPDATE_SUBTASK,
    POST_CREATE_EPIC, POST_UPDATE_EPIC,
    DELETE_TASK, DELETE_TASKS,
    DELETE_SUBTASK,
    DELETE_EPIC, DELETE_EPICS,
    UNKNOWN
}